### ISSUE TITLE
Could not find a valid gem 'opal-starter-kit' in any repository

### ISSUE THREAD

**Issue by illtellyoulater** [fkchang/opal-starter-kit#1]
gem install opal-starter-kit

ERROR:  Could not find a valid gem 'opal-starter-kit' (>= 0) in any repository
ERROR:  Possible alternatives: mmostarterkit, compass_ae_starter_kit, fidor_starter_kits, upstarter

**Comment by fkchang** [comment]
@jjgh I never got it to stage where I released a gem. That said, I've been meaning to revisit it. I definitely have to upgrade a lot of things

**Comment by illtellyoulater** [comment]
I apologize! Looking at the readme I was tricked into thinking that the gem was out there and that for some reason it was unavailable! Maybe I should just have looked at the _releases_ tab :) I did not mean to put pressure on your side! :)

**Comment by fkchang** [comment]
No worries, the fact that someone is interested is motivation to resume work.
